// The file the app's own "⬇ ดาวน์โหลดไฟล์ backup" button saves, committed so the server can
// prove its import accepts it (`server/test/owner-import.spec.ts`).
//
// The shop's history comes from the synthetic snapshot (test/fixtures/synthetic_snapshot_small.json,
// generated by `server/test/fixtures/synthetic-snapshot.ts`), loaded into a seed-free database
// — the API build's (`seedDemoData: false`) — and exported with the same
// `SnapshotRepository.exportSnapshot()` the Settings backup button calls. Only `exportedAt`
// is pinned, so the file is stable.
//
// If exportSnapshot()'s shape changes this test fails; regenerate the fixture with
//   UPDATE_APP_EXPORT_FIXTURE=1 flutter test test/app_export_fixture_test.dart
// and re-run the server's `owner-import.spec.ts` against it.

import 'dart:convert';
import 'dart:io';

import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:srisurart_pos/data/db/database.dart';
import 'package:srisurart_pos/data/repositories/snapshot_repository.dart';

const _fixture = 'test/fixtures/app_export_from_synthetic.json';

Future<String> _appExport() async {
  final db = AppDatabase(NativeDatabase.memory(), seedDemoData: false);
  try {
    final repo = SnapshotRepository(db);
    final snap = jsonDecode(
      await File('test/fixtures/synthetic_snapshot_small.json').readAsString(),
    ) as Map<String, dynamic>;
    await repo.importLegacyBackup(snap);
    final out = await repo.exportSnapshot();
    (out['__meta'] as Map)['exportedAt'] = '2026-10-07T00:00:00.000Z';
    return jsonEncode(out);
  } finally {
    await db.close();
  }
}

void main() {
  test('the backup button\'s file matches the fixture the server imports', () async {
    final exported = await _appExport();
    if (Platform.environment['UPDATE_APP_EXPORT_FIXTURE'] == '1') {
      await File(_fixture).writeAsString('$exported\n');
    }
    final committed = (await File(_fixture).readAsString()).trim();
    expect(exported, committed);
  });
}
