// #185 — the client half of the import path: `importLegacyBackup()` on a synthetic shop
// snapshot generated by `server/test/fixtures/synthetic-snapshot.ts` (seeded, committed
// as test/fixtures/synthetic_snapshot_small.json; the server unit test fails if the file
// and the generator drift apart).
//
// The sample is the `realistic` profile: it carries the rows the Drift build really
// produces — legacy `zone` products, explicit nulls, hard-deleted products / customers /
// mechanics that history still references, a category the list lost — and asserts the
// importer takes all of it and every ledger number survives.
//
// To run the same assertions on another file (the shop's real snapshot, never committed):
//   SNAPSHOT_FILE=/path/to/backup.json flutter test test/synthetic_snapshot_import_test.dart

import 'dart:convert';
import 'dart:io';

import 'package:drift/drift.dart' hide isNull;
import 'package:drift/native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:srisurart_pos/data/db/database.dart';
import 'package:srisurart_pos/data/repositories/snapshot_repository.dart';

const _zoneMap = {
  'Engine': 'เครื่องยนต์',
  'Electrical': 'ไฟฟ้า',
  'Oils': 'น้ำมัน',
  'Brakes': 'เบรก',
  'Body': 'ตัวถัง',
};

int _sat(dynamic v) => ((v as num? ?? 0) * 100).round();

List<Map<String, dynamic>> _list(dynamic v) => v is List
    ? v.whereType<Map>().map((e) => e.cast<String, dynamic>()).toList()
    : const [];

int _items(dynamic store) =>
    _list(store).fold(0, (n, x) => n + _list(x['items']).length);

void main() {
  final path =
      Platform.environment['SNAPSHOT_FILE'] ??
      'test/fixtures/synthetic_snapshot_small.json';
  late Map<String, dynamic> snap;
  late AppDatabase db;

  setUp(() async {
    snap = jsonDecode(await File(path).readAsString()) as Map<String, dynamic>;
    db = AppDatabase(NativeDatabase.memory());
    await SnapshotRepository(db).importLegacyBackup(snap);
  });

  tearDown(() => db.close());

  Future<int> count(TableInfo table) async =>
      (await db.select(table).get()).length;

  test('every store lands with the row count the file carries', () async {
    final history = _list(snap['sa_shift_history']);
    final drawer = snap['sa_cash_drawer'] is Map
        ? [(snap['sa_cash_drawer'] as Map).cast<String, dynamic>()]
        : <Map<String, dynamic>>[];
    final shifts = [...drawer, ...history];

    expect(await count(db.products), _list(snap['sa_products']).length);
    expect(await count(db.customers), _list(snap['sa_customers']).length);
    expect(await count(db.mechanics), _list(snap['sa_mechanics']).length);
    expect(await count(db.suppliers), _list(snap['sa_suppliers']).length);
    expect(await count(db.sales), _list(snap['sa_sales']).length);
    expect(await count(db.saleItems), _items(snap['sa_sales']));
    expect(await count(db.returns), _list(snap['sa_returns']).length);
    expect(await count(db.returnItems), _items(snap['sa_returns']));
    expect(await count(db.purchaseOrders), _list(snap['sa_pos']).length);
    expect(await count(db.poItems), _items(snap['sa_pos']));
    expect(await count(db.quotes), _list(snap['sa_quotes']).length);
    expect(await count(db.quoteItems), _items(snap['sa_quotes']));
    expect(await count(db.movements), _list(snap['sa_movements']).length);
    expect(
      await count(db.creditPayments),
      _list(snap['sa_credit_payments']).length,
    );
    expect(await count(db.shifts), shifts.length);
    expect(
      await count(db.drawerEntries),
      shifts.fold<int>(0, (n, s) => n + _list(s['entries']).length),
    );
    expect(await count(db.parkedSales), _list(snap['sa_parked']).length);
    expect(
      await count(db.categories),
      (snap['sa_categories'] as List).length,
    );
    final active = await (db.select(
      db.shifts,
    )..where((t) => t.isActive.equals(true))).get();
    expect(active.length, drawer.length);
  });

  test('stock, sales, points and credit balances match the file', () async {
    final products = await db.select(db.products).get();
    expect(
      products.fold<int>(0, (n, p) => n + p.stock),
      _list(snap['sa_products']).fold<int>(0, (n, p) => n + (p['stock'] as int)),
    );

    final sales = await db.select(db.sales).get();
    expect(
      sales.fold<int>(0, (n, s) => n + _sat(s.total)),
      _list(snap['sa_sales']).fold<int>(0, (n, s) => n + _sat(s['total'])),
    );

    final customers = {
      for (final c in await db.select(db.customers).get()) c.id: c,
    };
    for (final c in _list(snap['sa_customers'])) {
      final row = customers[c['id']]!;
      expect(row.points, c['points'], reason: 'points of ${c['code']}');
      expect(_sat(row.totalSpend), _sat(c['totalSpend']), reason: '${c['code']}');
    }

    final mechanics = {
      for (final m in await db.select(db.mechanics).get()) m.id: m,
    };
    for (final m in _list(snap['sa_mechanics'])) {
      expect(
        _sat(mechanics[m['id']]!.creditBalance),
        _sat(m['creditBalance']),
        reason: 'creditBalance of ${m['code']}',
      );
    }

    final payments = await db.select(db.creditPayments).get();
    expect(
      payments.fold<int>(0, (n, p) => n + _sat(p.amount)),
      _list(snap['sa_credit_payments']).fold<int>(0, (n, p) => n + _sat(p['amount'])),
    );
  });

  test('legacy zone migrates, null reads as absent, cost at sale survives', () async {
    final products = {
      for (final p in await db.select(db.products).get()) p.id: p,
    };
    for (final p in _list(snap['sa_products'])) {
      final row = products[p['id']]!;
      if (p['category'] == null && p['zone'] != null) {
        expect(row.category, _zoneMap[p['zone']] ?? p['zone']);
      }
      if (p.containsKey('compat') && p['compat'] == null) {
        expect(row.compat, isNull);
      }
    }

    final withCost = _list(snap['sa_sales'])
        .expand((s) => _list(s['items']))
        .where((i) => i['cost'] != null)
        .length;
    final items = await db.select(db.saleItems).get();
    expect(items.where((i) => i.costAtSale != null).length, withCost);
  });

  test('an export of the imported data has the same stores and field names', () async {
    final out = await SnapshotRepository(db).exportSnapshot();

    // Field names per store (union over rows, keys whose value is non-null — the
    // importer reads null as absent and the exporter omits it), plus nested `items[]`
    // and `entries[]` field names. Order is irrelevant.
    Set<String> fields(dynamic store) {
      final rows = store is Map ? [store] : (store is List ? store : const []);
      final names = <String>{};
      for (final r in rows.whereType<Map>()) {
        r.forEach((k, v) {
          if (v == null) return;
          names.add('$k');
          for (final nested in const ['items', 'entries']) {
            if (k == nested && v is List) {
              for (final it in v.whereType<Map>()) {
                it.forEach((nk, nv) {
                  if (nv != null) names.add('$k.$nk');
                });
              }
            }
          }
        });
      }
      return names;
    }

    // Documented, intended losses on this path — anything else is a regression:
    //  • `zone` — importLegacyBackup() migrates it into `category` and never stores it;
    //  • `__meta.synthetic` — the generator's own provenance note.
    const dropped = {
      'sa_products': {'zone'},
      '__meta': {'synthetic'},
    };
    final inKeys = snap.keys.where((k) => snap[k] != null).toSet();
    final outKeys = out.keys.where((k) => out[k] != null).toSet();
    expect(outKeys, inKeys);
    for (final key in inKeys) {
      if (snap[key] is String) continue; // sa_schema_version
      final expected = fields(snap[key])..removeAll(dropped[key] ?? const {});
      expect(fields(out[key]), expected, reason: 'field names of $key');
    }
  });

  test('an export of the imported data carries the same record counts', () async {
    final out = await SnapshotRepository(db).exportSnapshot();
    final before = (snap['__meta'] as Map)['recordCounts'] as Map;
    final after = (out['__meta'] as Map)['recordCounts'] as Map;
    for (final key in before.keys) {
      expect(after[key], before[key], reason: 'recordCounts.$key');
    }
  });
}
