// The wire conventions every ApiRepository shares (#56, ADR-0010).
//
// Three things live here and nowhere else, because two repositories getting
// them subtly different is exactly the "invariant ชุดที่สอง" ADR-0010 §3 bans:
//
//  1. **Money crosses the wire as a string** (`"1234.50"`, 02_API_SCREENS.md
//     §1.1). The server parses a JSON number too, but `0.1 + 0.2` is how a
//     receipt total ends up a satang off the paper in the customer's hand, so
//     the client sends the string form and never the double.
//  2. **Timestamps are ISO-8601 UTC** and become local `DateTime`s here.
//  3. **An `ApiException` must never reach a screen.** Checkout / Returns /
//     Cash Drawer all render a failure as
//     `e.toString().replaceFirst('Exception: ', '')` — see
//     `returns_screen.dart:238` and `cash_drawer_screen.dart:199` — and those
//     screens may not be touched (#56 AC1). `ApiException.toString()` would
//     print `ApiException(status: 409, code: …)` at the counter. So every
//     repository here wraps its call in [rethrowThai], which re-throws the
//     resolved Thai sentence as a plain `Exception` — the same shape the Drift
//     services throw.

import '../../../core/network/api_exception.dart';
import '../../../core/utils/ids.dart';

/// Parses a `NUMERIC` as the API hands it back (`"1234.50"`, or a JSON number
/// from a handler that skipped the string form). `null` → 0.
double money(Object? wire) {
  if (wire == null) return 0;
  if (wire is num) return wire.toDouble();
  return double.parse(wire as String);
}

/// Same as [money] but keeps `null` as `null` — for the nullable columns
/// (`physicalCash`, `mechanicCreditBalanceAfter`, `mechanicDelta`).
double? moneyOrNull(Object? wire) => wire == null ? null : money(wire);

/// Baht → the wire's two-decimal string. `1250.5` → `"1250.50"`.
///
/// Rounds through integer satang rather than `toStringAsFixed`, which is a
/// float formatting of a float and rounds half-to-even on some inputs; the
/// server's `toSatang` refuses anything with a third decimal, so a value that
/// formats a hair off is a 400 at the counter.
String wireMoney(num baht) {
  final satang = (baht * 100).round();
  final sign = satang < 0 ? '-' : '';
  final abs = satang.abs();
  return '$sign${abs ~/ 100}.${(abs % 100).toString().padLeft(2, '0')}';
}

/// ISO-8601 from the server → a local `DateTime`, which is what every Drift
/// `DateTimeColumn` in this app holds.
DateTime stamp(Object? wire) => DateTime.parse(wire as String).toLocal();

DateTime? stampOrNull(Object? wire) => wire == null ? null : stamp(wire);

/// A fresh `Idempotency-Key` header for one money/stock write.
///
/// One key per logical attempt, generated by the caller BEFORE the request and
/// reused verbatim on every retry of that same attempt — that is the whole
/// point of the header (`server/README.md` *Idempotency*). Generating it inside
/// a retry loop would hand the server a new key each time and ring the bill up
/// twice, which is #56 AC2.
Map<String, String> idempotencyKey() => {'Idempotency-Key': newId('idem')};

/// Runs [body] and converts an [ApiException] into the plain `Exception` the
/// screens already know how to display. Everything else (a `SocketException`,
/// a `TimeoutException`) is left alone: it is not a server verdict and has no
/// Thai sentence of its own.
Future<T> rethrowThai<T>(Future<T> Function() body) async {
  try {
    return await body();
  } on ApiException catch (e) {
    throw Exception(e.thaiMessage);
  }
}
